config/routes.rb
Rails.application.routes.draw do
  root 'top#main'
  get 'top/main'
  resources :products
  resources :cart_items, only: [:create, :destroy]
  resources :carts, only: [:show]

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cartitem
end

app/models/cartitem.rb
class Cartitem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_one :cartitem, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  def current_cart
    if session[:cart_id]
      cart = Cart.find(session[:cart_id])
    else
      cart = Cart.create
      session[:cart_id] = cart.id
    end
    cart
  end
  helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
    product = Product.find(params[:product_id])
    cart = current_cart
    cart.cartitem.create(cart_id: cart.id, product_id: product.id, qty: params[:qty])
    redirect_to products_path
  end
  
  def destroy
    product = Product.find(params[:id])
    cart = current_cart
    cart.cartitem.find_by(product_id: product.id).destroy
    redirect_to cart_path(current_cart.id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cartitems = current_cart.cartitem
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  def create
    @product = Product.new(name: params[:product][:name], price: params[:product][:price])
    @product.save
    redirect_to products_path
  end
  
  def destroy
    Product.find(params[:id]).destroy
    redirect_to products_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/show.html.erb
<h1>カートの中身</h1>

<table border="1">
  <tr>
    <th>商品名</th>
    <th>価格</th>
    <th>数量</th>
    <th>合計金額</th>
  </tr>
  
  <% sum = 0 %>
<% @cartitems.each do |i| %>
  <tr>
    <td><%= i.product.name %></td>
    <td><%= i.product.price %></td>
    <td><%= i.qty %></td>
    <td><%= i.product.price * i.qty %></td>
    <td><%= link_to 'カートから削除', cart_item_path(i.product_id), method: :delete %></td>
  </tr>
  
  <% sum = sum + i.product.price * i.qty %>
<% end %>
</table>
<p>
合計金額：<%= sum %>円
</p>

<p>
  <%= link_to '戻る', products_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>商品一覧ページ</h1>
<%= link_to '商品の追加', new_product_path %>
<%= link_to 'カートの表示', cart_path(current_cart.id) %>

<% @products.each do |p| %>
  <p>
  商品名：<%= p.name %>
  価格：<%= p.price %>円<br>
  <%= form_tag cart_items_path(product_id: p.id) do %>
    数量：<%= number_field_tag :qty, 1, size: 2 %>
    <%= submit_tag 'カートに入れる' %>
  <% end %>
  <%= link_to '削除', product_path(p), method: :delete %>
  </p><hr>
<% end %>

<p>
  <%= link_to '戻る', root_path %>
</p>

app/views/products/new.html.erb
<%= form_for @product do |p| %>
<p>
  <%= p.label :name, '商品名' %><br>
  <%= p.text_field :name %>
</p>
<p>
  <%= p.label :price, '価格' %><br>
  <%= p.number_field :price %>
</p>
<%= p.submit '登録' %>
<% end %>

<p>
  <%= link_to '戻る', products_path %>
</p>

app/views/top/main.html.erb
<h1>トップ画面</h1>

<p><%= link_to '商品一覧', products_path %></p>